datasets: narrativeqa_130772,infbench_qa_eng_130862,infbench_choice_eng_130862
demo_files: ',,'
generation_max_length: 100,10,10
input_max_length: 131072,131072,131072
max_test_samples: 100
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
output_dir: output/Llama-3.1-8B-Instruct
shots: 2
stop_new_line: false
test_files: ',,'
use_chat_template: true
