datasets: ruler_niah_mk_2,ruler_niah_mk_3,ruler_niah_mv,json_kv
demo_files: ',,,'
generation_max_length: 50,100,50,100
input_max_length: 131072,131072,131072,131072
max_test_samples: 100
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
output_dir: output/Llama-3.1-8B-Instruct
shots: 2
stop_new_line: false
test_files: data/ruler/niah_multikey_2/validation_131072.jsonl,data/ruler/niah_multikey_3/validation_131072.jsonl,data/ruler/niah_multivalue/validation_131072.jsonl,data/json_kv/test_k1800_dep6.jsonl
use_chat_template: false
