datasets: msmarco_rerank_psg
demo_files: data/msmarco/test_reranking_data_k10_dep3.jsonl
generation_max_length: '200'
input_max_length: '131072'
max_test_samples: 100
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
output_dir: output/Llama-3.1-8B-Instruct
shots: 2
stop_new_line: true
test_files: data/msmarco/test_reranking_data_k1000_dep3.jsonl
use_chat_template: false
